define: def/ICE.def

node: IP*|FRAG

copy_corpus: t

query: ([1]IP-SUB|IP-SUB=1*|IP-SUB=2*|IP-SUB=3*|IP-SUB=4*|IP-SUB=5*|IP-SUB=6*|IP-SUB=7*|IP-SUB=8*|IP-SUB=9*|IP-SUB-1*|IP-SUB-2*|IP-SUB-3*|IP-SUB-4*|IP-SUB-5*|IP-SUB-6*|IP-SUB-7*|IP-SUB-8*|IP-SUB-9*|IP-MAT|IP-MAT=1*|IP-MAT=2*|IP-MAT=3*|IP-MAT=4*|IP-MAT=5*|IP-MAT=6*|IP-MAT=7*|IP-MAT=8*|IP-MAT=9*|IP-MAT-1*|IP-MAT-2*|IP-MAT-3*|IP-MAT-4*|IP-MAT-5*|IP-MAT-6*|IP-MAT-7*|IP-MAT-8*|IP-MAT-9*|IP-INF|IP-INF=1*|IP-INF=2*|IP-INF=3*|IP-INF=4*|IP-INF=5*|IP-INF=6*|IP-INF=7*|IP-INF=8*|IP-INF=9*|IP-INF-1*|IP-INF-2*|IP-INF-3*|IP-INF-4*|IP-INF-5*|IP-INF-6*|IP-INF-7*|IP-INF-8*|IP-INF-9* idoms {1}CONJ) AND ([2]IP*|FRAG ISROOT)

append_label{1}: -ZZZ-BAD-CONJ
