### This is a modified version of txt2ipsd.sh to be used with Risamálheild,
### in which the texts already are split into sentences, tagged and lemmatized,
### with punctuation separated. This script assumes that .lemmatized files
### have already been generated by risamalheild_hreinsa.py.
### You can also run txt2ipsd-risamalheild-batch.sh, which in turn runs
### risamalheild_hreinsa.py and this script, instead of running this script directly.


### The following lines from txt2ipsd.sh are commented out because tags and lemmas
### are extracted from the Risamálheild data by risamalheild_hreinsa.py, but are
### included for reference.

#echo "Encoding special markup"
#python3 ./scripts/encodemarkup.py $1.tok $1.enc

#echo "Tagging using IceTagger"
#cat $1.enc | java -classpath "../IceNLP/IceNLPCore.jar" is.iclt.icenlp.runner.RunIceTagger > $1.tagged

#echo "Lemmatizing using Lemmald"
#cat $1.enc | java -Xmx256m -classpath "../IceNLP/IceNLPCore.jar" is.iclt.icenlp.runner.RunIceTagger -of 1 -lem > $1.lemmatized

## python3 ./scripts/joinlemma.py $1.tagged $1.lemmatized

###


### Here are the additions specific to this script

echo "Processing file with base filename \"$1\""

echo "Converting troublesome punctuation to markup"
python3 ./scripts/risamalheild_convert_punctuation.py $1.lemmatized $1.lemmatized
# reinstate - (HYPHEN-MINUS) in tags only (second field in .lemmatized file)
awk '/ / {gsub("\\(COM:dash\\)", "-", $2); print $0} !/ / {print $0}' $1.lemmatized > $1.lemmatizedx
#echo "Tagging dash as comma (,)"
#sed 's/ - / , /g' $1.lemmatizedx > $1.lemmatizedxx

echo "Encoding special markup"
python3 ./scripts/encodemarkup.py $1.lemmatizedxx $1.lemmatizedxxx

echo "Replacing troublesome tags (x, v, -) with adverb tag"
sed -E 's/ ([xv-]|99[A-Za-z0-9_-]+66) / aa /g' $1.lemmatizedxxx > $1.lemmatized

# Generate .tagged file from .lemmatized file
awk '/ / {print $1 " " $2} !/ / {print $0}' $1.lemmatized > $1.taggedx # file where line breaks need fixing
# changing single newlines to space and double newlines to single newlines
awk '{printf "%s ", $0}' $1.taggedx | sed 's/  /\
/g' > $1.tagged
#remove temporary file
#rm $1.taggedx

###


### Here the script continues identically to txt2ipsd.sh

echo "Parsing using IceParser"
cat $1.tagged | java -classpath "../IceNLP/IceNLPCore.jar" is.iclt.icenlp.runner.RunIceParser -f -l > $1.ipsdx

echo "Converting IceParser's ipsd output to labeled bracketing"
# Assumes .ipsd input and .psd output
python3 ./scripts/ipsd2psd.py $1

echo "Decoding special markup"
python ./scripts/decodemarkup.py $1.ipsd $1.ipsd

echo "Removing temporary files"
#rm $1.enc
#rm $1.tagged
#rm $1.lemmatized
#rm $1.ipsdx

echo "Done"
